//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArknightsResources.Operators.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArknightsResources.Operators.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;Operators&quot;
        ///    targetNamespace=&quot;http://schema.livestudio.com/Operators.xsd&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    xmlns=&quot;http://schema.livestudio.com/Operators.xsd&quot;
        ///    xmlns:mstns=&quot;http://schema.livestudio.com/Operators.xsd&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///&gt;
        ///  &lt;xs:element name=&quot;OperatorsList&quot; type=&quot;OperatorsList&quot;/&gt;
        ///
        ///  &lt;xs:complexType name=&quot;OperatorsList&quot;&gt;
        ///    &lt;xs:sequence maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;Op [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string OperatorsSchema {
            get {
                return ResourceManager.GetString("OperatorsSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [最后更新:2022年2月20日]
        ///aglina_boc
        ///aglina_summer
        ///amiya_epoque
        ///amiya_test
        ///amiya_winter
        ///amgoat_summer
        ///angel_kfc
        ///angel_wild
        ///ansel_summer
        ///aprl_wild
        ///archet_shining
        ///ardign_snow
        ///ash_rainbow6
        ///astesi_epoque
        ///astesi_shining
        ///ayer_boc
        ///beagle_boc
        ///beewax_epoque
        ///bibeak_winter
        ///billro_snow
        ///blackd_as
        ///blackd_winter
        ///blemsh_witch
        ///bldsk_witch
        ///bldsk_summer
        ///bluep_marthe
        ///bpipe_race
        ///brownb_kitchen
        ///bstalk_snow
        ///cammou_witch
        ///cast3_summer
        ///ccheal_epoque
        ///cerber_summer
        ///cerber_whirlwind
        ///cgbird_witch
        ///chen_nian
        ///c [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string 干员皮肤代号 {
            get {
                return ResourceManager.GetString("干员皮肤代号", resourceCulture);
            }
        }
    }
}
